name: smart_progress_dialog

description: "A Flutter package for showing customizable animated dialogs, alerts, snackbars, and loaders with Lottie support."

version: 0.0.3

homepage: https://github.com/akikadigital/smart_progress_dialog
repository: https://github.com/akikadigital/smart_progress_dialog

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

topics:
  - flutter
  - dialogs
  - progress
  - snackbar
  - alerts
