name: smart_progress_dialog

description: >
  A customizable Flutter dialog widget for showing animated progress, success,
  failure, and warning states with optional controller support, pull-to-refresh,
  and infinite scroll integration.

version: 0.0.2

homepage: https://github.com/akikadigital/smart_progress_dialog
repository: https://github.com/akikadigital/smart_progress_dialog

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

topics:
  - flutter
  - dialogs
  - toastr
  - animated
  - animated_dialogs
  - progress
  - snackbar
  - alerts
  - feedback
