name: smart_progress_dialog

description: "A Flutter package for showing customizable animated dialogs, alerts, snackbars, and loaders with Lottie support."

version: 0.0.6

homepage: https://github.com/akikadigital/smart_progress_dialog
repository: https://github.com/akikadigital/smart_progress_dialog
issue_tracker: https://github.com/akikadigital/smart_progress_dialog/issues
documentation: https://pub.dev/packages/smart_progress_dialog

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/success.json
    - assets/info.json
    - assets/warning.json
    - assets/error.json
    - assets/logo.png

topics:
  - flutter
  - dialogs
  - progress
  - snackbar
  - alerts
